### ISSUE TITLE
Please make cidr website responsive

### ISSUE THREAD

**Issue by pdmwu** [yuvadm/cidr.xyz#13] opened 2019-07-03 11:31 UTC
The cidr website is almost not usable on a smartphone. Bad when trying things out and you are not using a Desktop computer. Please make site responsive.

**Comment by jibin2706** [comment] 2019-07-05 05:22
#8 tries to solve it

**Comment by yuvadm** [comment] 2020-04-14 08:24
Duplicate of #4

**Closed by yuvadm** 2020-04-14 08:24 UTC
