### ISSUE TITLE
Incorrect results for cases like 0.0.0.0/30, 0.0.0.4/30

### ISSUE THREAD

**Issue by mvmn** [yuvadm/cidr.xyz#20] opened 2020-03-25 15:07 UTC
Looks like in some cases starting and ending IP addresses are excluded, and inconsistent result is returned, e.g. there starting IP is output as 0.0.0.5 and ending as 0.0.0.6 - which is 2 different IPs - but count is 4. This is for 0.0.0.4/30 - pretty sure starting IP should be 0.0.0.4 and ending 0.0.0.7.

See also screenshots:
<img width="1552" alt="Screenshot 2020-03-25 at 16 58 54" src="https://user-images.githubusercontent.com/1076779/77551354-eef18700-6eba-11ea-950e-8ecace170529.png">
<img width="1552" alt="Screenshot 2020-03-25 at 16 58 16" src="https://user-images.githubusercontent.com/1076779/77551364-f022b400-6eba-11ea-8670-0b2c598c9617.png">
<img width="1552" alt="Screenshot 2020-03-25 at 17 00 45" src="https://user-images.githubusercontent.com/1076779/77551365-f022b400-6eba-11ea-9d8d-819f8cef3d25.png">

**Comment by michaelreiser** [comment] 2020-03-31 21:18
/29 outputs the wrong start and end IP's too

**Comment by yuvadm** [comment] 2020-04-14 08:28
This seems like a duplicate of #10 and stems from the behavior of https://github.com/rs/node-netmask

I agree there are mismatches in how the data is presented with regards to the count and usable IPs, but any fixes should be reported and resolved upstream on `node-netmask`

**Comment by yuvadm** [comment] 2020-04-16 20:37
I'm open to continuing this discussion and might be willing to accept any PRs tackling this in elegant ways, but for now I'll close this issue.

**Closed by yuvadm** 2020-04-16 20:37 UTC
